version: "3.9"
services:
  db:
    image: mysql:8.3
    container_name: cinesphere-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinesphere
      MYSQL_USER: cinesphere_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
